### ISSUE TITLE
hey how can i use it with playwright typescript ?

### ISSUE THREAD

**Issue by Un1xCr3wR0x** [notune/captcha-solver#1]
i wanna use it with playwright typescript , is it possible ?

**Comment by notune** [comment]
It should be possible as long as you set headless to false like so: `const browser = await chromium.launch({ headless: false })`
But this repo doesn't auto detect captchas (yet). This would be easy to implement however, you would just have to adjust the code by perpetually checking if `findAndClick(reference_image_path='box.png', max_offset=5)` returns True and then run main.py without the findandclick part. Then just leave the code running and it should solve any captchas that it "sees".

**Comment by Un1xCr3wR0x** [comment]
the solvation part is written in python so i need to send the catcha challenge to the python code as an api then it should return the result then i have to use this result right ?

**Comment by notune** [comment]
As stated in the Readme this repo only relies on a visual approach. So it would probably easier to simply let this script run independently from the playwright, by either calling it each time if you detect a captcha, it will then click on the respective tiles. Or adjust the logic to detect captcha each x-seconds and run it completely independent from the playwright script.
